import type { Metadata } from "next";
import { AlertTriangle, Camera, Droplets, Gauge, Toilet, Volume2, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";

export const metadata: Metadata = { title: "Toilet Keeps Running: Cistern Fault Signs", description: "If a toilet keeps filling or running into the pan in Kensington or W8, identify the cistern behaviour and send the useful details.", alternates: { canonical: "/plumbing-problems/toilet-keeps-running" } };

export default function ToiletKeepsRunningPage() {
  return <><Header /><main className="problem-detail running-toilet-problem">
    <section className="problem-hero problem-hero-dark"><div className="site-shell"><ServiceBreadcrumbs current="Toilet keeps running" /><div className="running-hero-layout"><div><span className="problem-icon-large"><Toilet size={30} aria-hidden="true" /></span><span className="section-kicker">Toilet symptom</span><h1>Toilet keeps running?</h1><p>A toilet that continues to fill or run into the pan is usually best described through its cistern behaviour. It is not the same starting point as a blocked toilet with rising water.</p></div><div className="running-meter"><Volume2 size={25} aria-hidden="true" /><span>Listen for the pattern</span><strong>Constant, after flushing or intermittent?</strong></div></div></div></section>
    <ServiceSection eyebrow="Identify the pattern" title="Where is the water going?" className="problem-section-light"><div className="running-pattern-grid"><div><Droplets size={23} aria-hidden="true" /><h3>Into the pan</h3><p>Water can be heard or seen continuing to enter the bowl after the flush.</p></div><div><Gauge size={23} aria-hidden="true" /><h3>Cistern keeps filling</h3><p>The cistern does not settle, refills repeatedly or takes an unusually long time.</p></div><div><Volume2 size={23} aria-hidden="true" /><h3>Noisy or intermittent</h3><p>The toilet is quiet sometimes but starts running or humming without a full flush.</p></div></div></ServiceSection>
    <section className="running-timeline-section"><div className="site-shell"><span className="section-kicker">Describe when it happens</span><h2>What changed after the last flush?</h2><div className="running-timeline"><div><span>01</span><p>Flush the toilet only if it is safe and the water level is normal.</p></div><div><span>02</span><p>Notice whether the sound stops, continues or returns later.</p></div><div><span>03</span><p>Share whether the handle, button, cistern or water level looks different.</p></div></div></div></section>
    <ServiceSection eyebrow="Avoid making it worse" title="Keep the description practical" className="problem-section-stone"><div className="running-avoidance"><div><AlertTriangle size={22} aria-hidden="true" /><p>If water is running continuously, stop using the toilet and limit the source if you know how to do so safely.</p></div><div><Wrench size={22} aria-hidden="true" /><p>Do not force the flush control or dismantle the cistern to find a part.</p></div><div><Droplets size={22} aria-hidden="true" /><p>If water is escaping around the toilet, mention the location of the leak as well as the running sound.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="What to send in the enquiry" title="Cistern details are useful"><div className="running-details"><div className="running-detail-card"><Camera size={26} aria-hidden="true" /><h3>Photo or short description</h3><p>Show the visible cistern, flush plate or water around the base from a safe position.</p></div><ul><li>Does water run into the pan or only refill the cistern?</li><li>Is it constant, after flushing or intermittent?</li><li>Is the toilet still flushing normally?</li><li>Is there any water outside the toilet?</li><li>Which room and Kensington or W8 location?</li></ul></div></ServiceSection>
    <section className="running-service-note"><div className="site-shell"><Toilet size={24} aria-hidden="true" /><div><span className="section-kicker">Service route</span><h2>This is a toilet repair symptom.</h2><p>Use Toilet Repair for running water, filling and flush mechanism faults. Use Blocked Toilet only when the main issue is rising water, overflow or slow drainage caused by a blockage.</p></div></div></section>
    <ServiceSection eyebrow="Where this problem may lead" title="Continue with the right service"><RelatedLinks pagePath="/plumbing-problems/toilet-keeps-running" links={[]} /></ServiceSection>
    <EnquiryCTA pagePath="/plumbing-problems/toilet-keeps-running" heading="Send the running-toilet details." detail="Tell us where the water goes, when the sound starts and what the cistern does after flushing." message="Hi, my toilet keeps running in Kensington. The water is..." />
  </main></>;
}
