import type { Metadata } from "next";
import { AlertTriangle, Camera, Droplets, MapPin, Toilet, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";

export const metadata: Metadata = { title: "Toilet Won't Flush: Fault or Blockage?", description: "A toilet that will not flush in Kensington or W8 may be a flush or cistern fault, or a blockage. Compare the signs before sending an enquiry.", alternates: { canonical: "/plumbing-problems/toilet-wont-flush" } };

export default function ToiletWontFlushPage() {
  return <><Header /><main className="problem-detail flush-problem">
    <section className="problem-hero problem-hero-cream"><div className="site-shell"><ServiceBreadcrumbs current="Toilet will not flush" /><div className="problem-hero-layout"><div><span className="problem-icon-large"><Toilet size={30} aria-hidden="true" /></span><span className="section-kicker">Toilet symptom</span><h1>Toilet will not flush?</h1><p>First check whether the flush action is failing or the water is rising because the toilet is blocked. That distinction sends the enquiry to the right starting point.</p></div><div className="flush-question-card"><strong>What happens after you press the button or handle?</strong><span>No movement, a weak flush, rising water or a cistern that will not fill all point to different descriptions.</span></div></div></div></section>
    <ServiceSection eyebrow="Choose what you see" title="Which flush symptom matches?" className="problem-section-light"><div className="flush-symptom-grid"><div><Wrench size={23} aria-hidden="true" /><h3>Button or handle does nothing</h3><p>The control is loose, stiff or no longer moves the flush mechanism.</p></div><div><Droplets size={23} aria-hidden="true" /><h3>Weak or incomplete flush</h3><p>The cistern empties but the flush is weaker than usual.</p></div><div><Toilet size={23} aria-hidden="true" /><h3>Cistern will not fill</h3><p>The toilet may flush once but does not refill or is slow to refill.</p></div><div><AlertTriangle size={23} aria-hidden="true" /><h3>Water rises or waste stays</h3><p>This points more towards a blocked toilet route than a flush mechanism fault.</p></div></div></ServiceSection>
    <section className="flush-choice-section"><div className="site-shell"><span className="section-kicker">The important distinction</span><h2>Flush fault or blocked toilet?</h2><div className="flush-choice-grid"><div><Wrench size={24} aria-hidden="true" /><h3>Toilet repair</h3><p>Use this route when the handle, button, cistern, fill or flush mechanism is the main issue and water is not primarily rising from a blockage.</p><a className="text-arrow-link" href="/services/toilet-repair">Toilet repair service <span aria-hidden="true">→</span></a></div><div><AlertTriangle size={24} aria-hidden="true" /><h3>Blocked toilet</h3><p>Use this route when the bowl rises, overflows or drains slowly because waste or water is not clearing.</p><a className="text-arrow-link" href="/services/blocked-toilet">Blocked toilet service <span aria-hidden="true">→</span></a></div></div></div></section>
    <ServiceSection eyebrow="Before sending the enquiry" title="Safe, simple checks" className="problem-section-stone"><div className="safe-note-row"><div><AlertTriangle size={21} aria-hidden="true" /><p>Do not keep flushing if the water level is rising.</p></div><div><Wrench size={21} aria-hidden="true" /><p>Do not force a stuck handle or button.</p></div><div><Droplets size={21} aria-hidden="true" /><p>Describe what the cistern does after the flush action, rather than guessing the part.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="What to send" title="Details that make the fault clearer"><div className="flush-details"><div><Camera size={23} aria-hidden="true" /><h3>Photo if safe</h3><p>Show the cistern, button or handle and any visible water around the toilet.</p></div><div><MapPin size={23} aria-hidden="true" /><h3>Room and location</h3><p>Include the room and your Kensington or W8 location.</p></div><div><Toilet size={23} aria-hidden="true" /><h3>What happens next</h3><p>Say whether the bowl clears, rises, stays full or the cistern continues to fill.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="Where this problem may lead" title="Use the service page that matches the cause"><RelatedLinks pagePath="/plumbing-problems/toilet-wont-flush" links={[]} /></ServiceSection>
    <EnquiryCTA pagePath="/plumbing-problems/toilet-wont-flush" heading="Describe what happens when you flush." detail="Tell us what the control does, what the water level does and whether anything is clearing." message="Hi, my toilet will not flush in Kensington. When I press the button or handle..." />
  </main></>;
}
