import type { Metadata } from "next";
import { AlertTriangle, Camera, Droplets, MapPin, Power, Siren, Toilet, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";
import { ServiceStructuredData } from "../../_components/StructuredData";

export const metadata: Metadata = {
  title: "Emergency Plumber Kensington | Urgent Plumbing Problems",
  description: "Water spreading, a failed fitting or a toilet problem in Kensington? Start with safe steps, then send the room, symptom and useful photos.",
  alternates: { canonical: "/services/emergency-plumber" },
};

export default function EmergencyPlumberPage() {
  return <><Header /><ServiceStructuredData name="Emergency plumbing enquiry" description="Send a clear emergency plumbing enquiry for Kensington and W8, with practical steps to take before sharing the details." path="/services/emergency-plumber" /><main className="service-detail emergency-service">
    <section className="service-hero"><div className="site-shell"><ServiceBreadcrumbs current="Emergency plumber" currentPath="/services/emergency-plumber" /><div className="service-hero-grid"><div><span className="service-icon-large"><Siren size={30} aria-hidden="true" /></span><span className="section-kicker">Urgent plumbing enquiry</span><h1>Emergency plumbing problem in Kensington?</h1><p>When water is spreading, a fitting has failed or a toilet cannot be used, start by making the situation safe and send the clearest details you can.</p></div><div className="service-hero-note"><AlertTriangle size={24} aria-hidden="true" /><strong>First priority</strong><span>Protect people and the property before describing the issue.</span></div></div></div></section>
    <ServiceSection eyebrow="Make the urgency clear" title="What makes this urgent?" className="service-section-light"><div className="choice-grid">{[{ title: "Water is spreading", text: "A leak is reaching flooring, ceilings, sockets or other rooms.", icon: Droplets }, { title: "A fitting has failed", text: "A pipe, valve, tank or connection is releasing water unexpectedly.", icon: Wrench }, { title: "The toilet cannot be used", text: "The bowl is rising, overflowing or will not clear after a flush.", icon: Toilet }].map(({ title, text, icon: Icon }) => <div className="choice-card" key={title}><Icon size={25} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></div>)}</div></ServiceSection>
    <ServiceSection eyebrow="Before you send the enquiry" title="Immediate safe actions" className="service-section-dark"><div className="action-list"><div><span>1</span><p>If it is safe, stop using the affected tap, toilet, shower or appliance.</p></div><div><span>2</span><p>Keep people away from wet floors and move belongings away from the water.</p></div><div><span>3</span><p>If water is near electrics, avoid contact and seek appropriate urgent help.</p></div><div><span>4</span><p>Take a quick photo from a safe position, then send the details on WhatsApp.</p></div></div><Power className="action-watermark" size={120} aria-hidden="true" /></ServiceSection>
    <ServiceSection eyebrow="Common urgent situations" title="What can an urgent enquiry cover?"><div className="split-list"><ul><li>Water coming through a ceiling</li><li>A burst or visibly damaged pipe</li><li>A radiator or valve leaking onto flooring</li></ul><ul><li>An overflowing toilet that will not settle</li><li>A failed tap or connection that cannot be isolated</li><li>Sudden water loss affecting part of a property</li></ul></div></ServiceSection>
    <ServiceSection eyebrow="Help the next step" title="What to send on WhatsApp?" className="service-section-stone"><div className="details-grid"><div><Camera size={22} aria-hidden="true" /><h3>A photo if safe</h3><p>Show the fitting, affected area and where the water is travelling.</p></div><div><MapPin size={22} aria-hidden="true" /><h3>Your location</h3><p>Say Kensington or your W8 postcode area and identify the room.</p></div><div><AlertTriangle size={22} aria-hidden="true" /><h3>What changed</h3><p>Explain when it started, what is still happening and any action already taken.</p></div></div></ServiceSection>
    <section className="service-context"><div className="site-shell"><MapPin size={23} aria-hidden="true" /><div><span className="section-kicker">Kensington / W8</span><h2>Keep the location specific.</h2><p>A clear area and postcode context helps an enquiry start with the right information. This site is focused on Kensington, London.</p></div></div></section>
    <ServiceSection eyebrow="Continue browsing" title="Related services"><RelatedLinks pagePath="/services/emergency-plumber" links={[]} /></ServiceSection>
    <EnquiryCTA pagePath="/services/emergency-plumber" heading="Send the urgent details while they are clear." detail="Describe what is happening, where it is happening and what you have done to make it safe." message="Hi, I have an urgent plumbing problem in Kensington. The issue is..." />
  </main></>;
}
