import type { Metadata } from "next";
import { AlertTriangle, Camera, Droplets, Lightbulb, MapPin, Power, ShowerHead } from "lucide-react";
import Header from "../../_components/Header";
import VisualAsset from "../../_components/VisualAsset";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";

export const metadata: Metadata = { title: "Water Coming Through Your Ceiling", description: "Water coming through a ceiling in Kensington or W8? Start with safe steps, avoid electrical risks and send clear photos and location details.", alternates: { canonical: "/plumbing-problems/water-coming-through-ceiling" } };

export default function WaterComingThroughCeilingPage() {
  return <><Header /><main className="problem-detail ceiling-problem">
    <section className="problem-hero problem-hero-dark"><div className="site-shell"><ServiceBreadcrumbs current="Water coming through the ceiling" /><div className="problem-hero-layout"><div><span className="problem-icon-large"><Droplets size={30} aria-hidden="true" /></span><span className="section-kicker">Plumbing problem</span><h1>Water coming through the ceiling?</h1><p>If water is entering from above, treat it as a leak to make safe and describe which room is above and below. Do not wait to identify the hidden source before limiting damage.</p></div><div className="problem-answer-card"><AlertTriangle size={24} aria-hidden="true" /><strong>First priority</strong><span>Keep people away from wet areas and avoid electrics near the water.</span></div></div></div></section>
    <section className="ceiling-safety-visual-section"><div className="site-shell"><VisualAsset alt="" name="ceiling-water-safety" /></div></section>
    <ServiceSection eyebrow="What to do now" title="Limit damage safely" className="problem-section-stone"><div className="safe-step-grid"><div><span>01</span><Power size={21} aria-hidden="true" /><p>If you know the affected water supply and it is safe, turn it off.</p></div><div><span>02</span><Lightbulb size={21} aria-hidden="true" /><p>If water is near lights, sockets or appliances, avoid contact with electrics and leave the area safe.</p></div><div><span>03</span><Droplets size={21} aria-hidden="true" /><p>Move belongings away and catch drips only if you can do so without standing in danger.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="Think about the route" title="Where might the leak be coming from?"><div className="ceiling-route-grid"><div><ShowerHead size={23} aria-hidden="true" /><h3>Room above</h3><p>It may relate to a bathroom, shower, toilet, bath, basin or pipework in the room above.</p></div><div><Droplets size={23} aria-hidden="true" /><h3>Nearby plumbing</h3><p>Water can travel along ceilings and joists, so the first damp patch may not be directly below the source.</p></div><div><MapPin size={23} aria-hidden="true" /><h3>Communal or neighbouring area</h3><p>In a flat, note whether the water could be from another property or a shared area and contact the relevant landlord or managing agent where appropriate.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="Make the enquiry useful" title="What should you photograph and describe?" className="problem-section-light"><div className="problem-details-layout"><div className="problem-photo-card"><Camera size={27} aria-hidden="true" /><h3>Show the ceiling and surroundings</h3><p>From a safe, dry position, show the stain, drip, light fitting, wall edge and any visible route of the water.</p></div><ul><li>Which room is affected and what is directly above it?</li><li>When did you first see the water and is it still appearing?</li><li>Was a bathroom, shower, toilet, bath or appliance being used?</li><li>Is water close to a light, socket or appliance?</li><li>Your Kensington or W8 location</li></ul></div></ServiceSection>
    <section className="problem-decision-strip"><div className="site-shell"><span className="section-kicker">Choose the service route</span><h2>A ceiling leak needs the right context.</h2><p>Use Leak Repair for the water source and damage-limitation enquiry. If water is spreading or the situation is unsafe, use the Emergency Plumber route as well.</p></div></section>
    <ServiceSection eyebrow="Where this problem may lead" title="Continue with the closest plumbing route"><RelatedLinks pagePath="/plumbing-problems/water-coming-through-ceiling" links={[]} /></ServiceSection>
    <EnquiryCTA pagePath="/plumbing-problems/water-coming-through-ceiling" heading="Send the ceiling leak details." detail="Describe the rooms, water movement, safe actions already taken and any useful photos." message="Hi, water is coming through a ceiling in Kensington. It is affecting..." />
  </main></>;
}
