import type { Metadata } from "next";
import { AlertTriangle, Bath, CircleAlert, Droplets, MapPin, MessageCircle, Toilet, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";
import { ServiceStructuredData } from "../../_components/StructuredData";

export const metadata: Metadata = {
  title: "Blocked Toilet Enquiries Kensington",
  description: "Describe a slow, rising, non-flushing or recurring toilet blockage in Kensington and send the useful details on WhatsApp.",
  alternates: { canonical: "/services/blocked-toilet" },
};

export default function BlockedToiletPage() {
  return <><Header /><ServiceStructuredData name="Blocked toilet enquiry" description="Describe a slow, rising, non-flushing or recurring toilet blockage in Kensington and send the useful details on WhatsApp." path="/services/blocked-toilet" /><main className="service-detail toilet-service">
    <section className="service-hero service-hero-burgundy"><div className="site-shell"><ServiceBreadcrumbs current="Blocked toilet" currentPath="/services/blocked-toilet" /><div className="toilet-hero"><div><span className="service-icon-large"><Toilet size={30} aria-hidden="true" /></span><span className="section-kicker">Blocked toilet enquiry</span><h1>Toilet slow, rising or not flushing?</h1><p>Start by describing the exact symptom. That helps separate a simple toilet issue from signs that other drainage fixtures may also be affected.</p></div><div className="toilet-symptom-badge"><CircleAlert size={24} aria-hidden="true" /><span>Do not keep flushing if the water is rising.</span></div></div></div></section>
    <ServiceSection eyebrow="Choose the closest symptom" title="What is the toilet doing?" className="toilet-symptoms"><div className="symptom-row">{[{ title: "Slow flush", text: "The water clears, but more slowly than usual.", icon: Droplets }, { title: "Rising water", text: "The level rises after flushing or drains very slowly.", icon: AlertTriangle }, { title: "Will not flush", text: "The handle, button or flush action does not clear the bowl.", icon: Toilet }, { title: "Recurring blockage", text: "The same problem returns after temporarily clearing.", icon: Wrench }].map(({ title, text, icon: Icon }) => <div className="symptom-card" key={title}><Icon size={24} aria-hidden="true" /><strong>{title}</strong><p>{text}</p></div>)}</div></ServiceSection>
    <ServiceSection eyebrow="Avoid making it worse" title="What not to do" className="service-section-warning"><div className="warning-list"><div><AlertTriangle size={22} aria-hidden="true" /><p>Do not keep flushing when the water level is rising or close to overflowing.</p></div><div><Wrench size={22} aria-hidden="true" /><p>Do not force the handle, button or visible fitting if it is sticking.</p></div><div><CircleAlert size={22} aria-hidden="true" /><p>Do not mix different cleaning products or use unknown chemicals in the bowl.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="One fixture or several?" title="A useful distinction" className="service-section-light"><div className="fixture-comparison"><article><span className="fixture-icon"><Toilet size={23} aria-hidden="true" /></span><h3>Only this toilet</h3><p>If sinks, baths and other toilets are draining normally, describe this toilet’s flush, water level and recent changes.</p><ul><li>One bowl affected</li><li>Other fixtures appear normal</li></ul></article><article><span className="fixture-icon"><Bath size={23} aria-hidden="true" /></span><h3>Several fixtures</h3><p>If more than one fixture is slow, gurgling or backing up, mention that early in the enquiry.</p><ul><li>Multiple fixtures affected</li><li>Shared drainage may be relevant</li></ul></article></div></ServiceSection>
    <ServiceSection eyebrow="Make the problem easy to understand" title="What information helps?"><div className="toilet-details"><div className="toilet-detail-list"><div><MessageCircle size={21} aria-hidden="true" /><span>Say when it started and whether it is getting worse.</span></div><div><MapPin size={21} aria-hidden="true" /><span>Include the room and Kensington or W8 location.</span></div><div><Droplets size={21} aria-hidden="true" /><span>Describe the water level, smell, noise or visible overflow.</span></div></div><div className="toilet-note"><Toilet size={28} aria-hidden="true" /><h3>A photo can help</h3><p>If safe and appropriate, show the bowl and surrounding area without touching the water.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="Look beyond the toilet" title="When might wider drainage be involved?" className="service-section-stone"><p className="section-lead">A blockage may deserve a wider description when sinks, baths or another toilet are also slow, when water backs up elsewhere, or when gurgling happens across more than one fixture. Include those observations rather than treating them as separate problems.</p><div className="drainage-signs"><span><Bath size={20} aria-hidden="true" /> Sink or bath drains slowly</span><span><Droplets size={20} aria-hidden="true" /> Water backs up elsewhere</span><span><CircleAlert size={20} aria-hidden="true" /> Gurgling from several fixtures</span></div></ServiceSection>
    <ServiceSection eyebrow="Related routes" title="Keep exploring the right starting point"><RelatedLinks links={[{ href: "/services/emergency-plumber", label: "Emergency plumber", description: "For an overflowing or urgent plumbing situation." }, { href: "/plumbing-problems#problem-list", label: "Plumbing problems", description: "Compare toilet and wider drainage symptoms." }, { href: "/services", label: "All services", description: "Return to the main service list." }]} /></ServiceSection>
    <section className="service-context"><div className="site-shell"><MapPin size={23} aria-hidden="true" /><div><span className="section-kicker">Kensington / W8</span><h2>Give the location with the symptom.</h2><p>Kensington and W8 context helps keep the enquiry clear without needing to guess the cause of the blockage.</p></div></div></section>
    <EnquiryCTA heading="Describe the toilet problem before trying more." detail="Share the symptom, whether other fixtures are affected and anything visible around the toilet." message="Hi, I have a blocked toilet problem in Kensington. The symptom is..." />
  </main></>;
}
