import type { Metadata } from "next";
import { AlertTriangle, Camera, Droplets, Gauge, ShowerHead, Thermometer, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";

export const metadata: Metadata = { title: "Shower Going Hot and Cold | Temperature & Flow", description: "Shower temperature changing in Kensington? Describe the pattern, flow and any visible fitting symptoms to choose the most relevant plumbing route.", alternates: { canonical: "/plumbing-problems/shower-going-hot-and-cold" } };

export default function ShowerGoingHotAndColdPage() {
  return <><Header /><main className="problem-detail shower-temperature-problem">
    <section className="problem-hero problem-hero-burgundy"><div className="site-shell"><ServiceBreadcrumbs current="Shower going hot and cold" /><div className="shower-problem-hero"><div><span className="problem-icon-large"><Thermometer size={30} aria-hidden="true" /></span><span className="section-kicker">Shower symptom</span><h1>Shower going hot and cold?</h1><p>Note when the temperature changes and whether the shower pressure or other bathroom outlets also change. Those details help separate a shower-specific plumbing symptom from a wider hot-water question.</p></div><div className="temperature-rail"><span><Thermometer size={20} aria-hidden="true" /> Temperature changes</span><span><Gauge size={20} aria-hidden="true" /> Flow or pressure</span></div></div></div></section>
    <ServiceSection eyebrow="Start with the pattern" title="What is changing?" className="problem-section-light"><div className="temperature-pattern-grid"><div><Thermometer size={23} aria-hidden="true" /><h3>Hot, then cold</h3><p>The water changes temperature while the shower is being used.</p></div><div><Gauge size={23} aria-hidden="true" /><h3>Pressure changes too</h3><p>The flow weakens or changes at the same time as the temperature.</p></div><div><Droplets size={23} aria-hidden="true" /><h3>Other taps are normal</h3><p>The symptom appears limited to the shower rather than the whole property.</p></div><div><Wrench size={23} aria-hidden="true" /><h3>Control or fitting issue</h3><p>A handle, valve, hose or shower head is loose, stiff or leaking.</p></div></div></ServiceSection>
    <section className="temperature-decision-section"><div className="site-shell"><span className="section-kicker">Answer the useful question first</span><h2>Shower plumbing or wider heating?</h2><div className="temperature-decision"><div><ShowerHead size={25} aria-hidden="true" /><h3>Shower-specific symptom</h3><p>If other taps are normal and the change is limited to the shower, describe its controls, head, hose, pressure and temperature pattern.</p><a className="text-arrow-link" href="/services/shower-repair">Shower repair service <span aria-hidden="true">→</span></a></div><div><Thermometer size={25} aria-hidden="true" /><h3>Wider hot-water question</h3><p>If several hot-water outlets change or the property has a wider heating concern, say so clearly. This page does not make boiler or gas repair claims.</p><a className="text-arrow-link" href="/services/bathroom-plumbing">Bathroom plumbing context <span aria-hidden="true">→</span></a></div></div></div></section>
    <ServiceSection eyebrow="Do not ignore these signs" title="Pause and describe what you can see" className="problem-section-stone"><div className="temperature-warning-grid"><div><AlertTriangle size={22} aria-hidden="true" /><p>Water is escaping into a wall, ceiling or floor.</p></div><div><Droplets size={22} aria-hidden="true" /><p>The shower tray is filling or drainage is becoming very slow.</p></div><div><Wrench size={22} aria-hidden="true" /><p>A control, hose or fitting is unsafe to operate or visibly damaged.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="What to send" title="Photos and details that help"><div className="temperature-details"><div><Camera size={26} aria-hidden="true" /><h3>Show the shower</h3><p>A photo of the controls, head, hose, tray or visible leak can show the affected fitting.</p></div><ul><li>How long before the temperature changes?</li><li>Does pressure change at the same time?</li><li>Are other taps and bathroom fixtures normal?</li><li>Is the shower leaking or draining slowly?</li><li>Your Kensington or W8 location</li></ul></div></ServiceSection>
    <ServiceSection eyebrow="Where this problem may lead" title="Choose the closest route"><RelatedLinks pagePath="/plumbing-problems/shower-going-hot-and-cold" links={[]} /></ServiceSection>
    <EnquiryCTA pagePath="/plumbing-problems/shower-going-hot-and-cold" heading="Describe when the shower changes." detail="Tell us the temperature pattern, shower-only pressure, other outlet behaviour and any visible leak or drainage issue." message="Hi, my shower is going hot and cold in Kensington. The change happens..." />
  </main></>;
}
