import type { Metadata } from "next";
import { Bath, Droplets, ShowerHead, Toilet, Wrench } from "lucide-react";
import Header from "../../_components/Header";
import { EnquiryCTA, RelatedLinks, ServiceBreadcrumbs, ServiceSection } from "../../_components/ServicePrimitives";
import { ServiceStructuredData } from "../../_components/StructuredData";

export const metadata: Metadata = {
  title: "Bathroom Plumbing Kensington | Basins, Toilets, Baths & Showers",
  description: "Bathroom plumbing problem in Kensington? Start with the basin, bath, shower, toilet or visible leak, then send the room and fixture details.",
  alternates: { canonical: "/services/bathroom-plumbing" },
};

export default function BathroomPlumbingPage() {
  return <><Header /><ServiceStructuredData name="Bathroom plumbing enquiry" description="Describe a basin, bath, shower, toilet or bathroom leak enquiry in Kensington and W8 with useful fixture details." path="/services/bathroom-plumbing" /><main className="service-detail bathroom-service">
    <section className="service-hero service-hero-cream"><div className="site-shell"><ServiceBreadcrumbs current="Bathroom plumbing" /><div className="bathroom-hero-layout"><div><span className="service-icon-large"><Bath size={30} aria-hidden="true" /></span><span className="section-kicker">Bathroom plumbing enquiry</span><h1>Which bathroom fixture is affected?</h1><p>Start with the room and the fixture you can see. A clear description of a basin, bath, shower, toilet or bathroom leak helps make the enquiry useful from the beginning.</p></div><div className="bathroom-hero-prompt"><span>Room first</span><strong>Bathroom fixture</strong><small>Then describe what changed.</small></div></div></div></section>
    <ServiceSection eyebrow="Choose the closest fixture" title="What needs attention?" className="service-section-light"><div className="bathroom-fixture-grid">{[{ title: "Basin or sink", text: "A tap, waste, trap, connection or leak around the basin.", icon: Droplets }, { title: "Bath", text: "Bath taps, waste, overflow, seal or pipework symptoms.", icon: Bath }, { title: "Shower", text: "A shower pressure, temperature, leak or drainage concern.", icon: ShowerHead }, { title: "Toilet", text: "A toilet flush, cistern or leak fault, or a suspected blockage.", icon: Toilet }, { title: "Bathroom pipework", text: "Visible pipe, valve or connection problems in the room.", icon: Wrench }].map(({ title, text, icon: Icon }) => <article className="bathroom-fixture-card" key={title}><Icon size={25} aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></ServiceSection>
    <ServiceSection eyebrow="Look for the visible symptom" title="Bathroom leaks can appear away from the source"><div className="bathroom-leak-layout"><div className="bathroom-leak-list"><div><Droplets size={22} aria-hidden="true" /><span>Water around a tap, basin, bath or shower fitting</span></div><div><Droplets size={22} aria-hidden="true" /><span>Dampness below a bathroom or near an adjoining room</span></div><div><Wrench size={22} aria-hidden="true" /><span>A wet valve, waste, trap or exposed connection</span></div></div><div className="bathroom-leak-note"><h3>Say where you first saw the water</h3><p>The first visible point may not be the source. Include what was being used, whether the water is constant and which room is below or beside it.</p></div></div></ServiceSection>
    <ServiceSection id="basin-sink" eyebrow="Basin / sink plumbing enquiries" title="Describe the basin, connection or visible water" className="service-section-stone"><div className="pipework-guide"><div><Droplets size={25} aria-hidden="true" /><h3>What to look for safely</h3><p>A basin or sink enquiry can start with water around the tap base, trap, waste pipe, flexible connection or the floor beneath the fixture. This route is for visible plumbing context, not a claim of drain-unblocking work.</p></div><ul><li>Is it a basin or kitchen sink?</li><li>Where is the water first visible?</li><li>Does it happen while the tap is used?</li><li>Can you photograph the fitting and surrounding pipework safely?</li></ul></div></ServiceSection>
    <section className="bathroom-enquiry-section"><div className="site-shell"><span className="section-kicker">Choose the right wording</span><h2>Repair, replacement or room enquiry?</h2><div className="bathroom-enquiry-columns"><div><span className="enquiry-column-number">01</span><h3>Existing fixture problem</h3><p>Use this route for a leak, failed fitting, poor drainage or a fixture that is not working as expected.</p></div><div><span className="enquiry-column-number">02</span><h3>Bathroom plumbing change</h3><p>If you are considering a refurbishment or fixture change, describe the room, the existing plumbing and what you would like to discuss. Avoid assuming the work or scope before it is assessed.</p></div></div></div></section>
    <ServiceSection eyebrow="Make the enquiry clear" title="What details should you send?" className="service-section-stone"><div className="bathroom-details-grid"><div><strong>Room and fixture</strong><p>Say which bathroom and whether it is the basin, bath, shower, toilet or pipework.</p></div><div><strong>Visible symptom</strong><p>Describe the water, drainage, temperature, pressure, noise or fitting behaviour.</p></div><div><strong>Photo if useful</strong><p>Show the fixture and surrounding floor, wall or connection from a safe position.</p></div><div><strong>Kensington or W8</strong><p>Include the local area context so the enquiry starts with the right location.</p></div></div></ServiceSection>
    <ServiceSection eyebrow="Useful if the symptom is specific" title="Go deeper only when the symptom is clear"><RelatedLinks pagePath="/services/bathroom-plumbing" links={[]} /></ServiceSection>
    <section className="service-context"><div className="site-shell"><Bath size={23} aria-hidden="true" /><div><span className="section-kicker">Kensington / W8</span><h2>Describe the room before the solution.</h2><p>A Kensington or W8 location, fixture name and visible symptom are enough to make a useful starting enquiry without making an unsupported diagnosis.</p></div></div></section>
    <EnquiryCTA pagePath="/services/bathroom-plumbing" heading="Send a bathroom plumbing enquiry." detail="Tell us which fixture is affected, what you can see and where the bathroom is in Kensington or W8." message="Hi, I have a bathroom plumbing problem in Kensington. The affected fixture is..." />
  </main></>;
}
